# permissions for end users to view configmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmonitor-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - configmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - configmonitors/status
  verbs:
  - get
